InstaFit/Models/Fitness.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaFit.Models
{
    public class Fitness
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Location { get; set; }
    }
}

InstaFit/Models/FitnessPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaFit.Models
{
    public class FitnessPost
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Location { get; set; }
    }
}

InstaFit/Models/Interfaces/IFit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaFit.Models.Interfaces
{
    public interface IFit
    {
        // Delete the post
        Task DeleteAsync(int id);
        // Search or Find
        Task<FitnessPost> FindFitnessPost(int id);
        // Get all posts
        Task<List<FitnessPost>> GetFitnessPosts();
        // Save the post
        Task SaveAsync(FitnessPost fitnessPost);
    }
}

InstaFit/Models/Services/FitMangementService.cs
using InstaFit.Data;
using InstaFit.Models.Interfaces;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace InstaFit.Models.Services
{
    public class FitMangementService : IFit
    {
        private readonly InstaDbContext _context;

        public FitMangementService(InstaDbContext context)
        {
            _context = context;
        }
        public async Task DeleteAsync(int id)
        {
            FitnessPost fitnessPost = await _context.FitnessPosts.FindAsync(id);
            if(fitnessPost != null)
            {
                _context.Remove(fitnessPost);
                await _context.SaveChangesAsync();
            }
        }

        public async Task<FitnessPost> FindFitnessPost(int id)
        {
            FitnessPost fitnessPost = await _context.FitnessPosts.FirstOrDefaultAsync(m => m.ID == id);

            return fitnessPost;
        }

        public Task<List<FitnessPost>> GetFitnessPosts()
        {
            return _context.FitnessPosts.ToListAsync();
        }

        public async Task SaveAsync(FitnessPost fitnessPost)
        {
        if (await _context.FitnessPosts.FirstOrDefaultAsync(m => m.ID == fitnessPost.ID) == null)
            {
                _context.FitnessPosts.Add(fitnessPost);
            }
            else
            {
                _context.FitnessPosts.Update(fitnessPost);
            }
            await _context.SaveChangesAsync();
        }
    }
}

InstaFit/Models/utilites/Blob.cs
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaFit.Models.utilites
{
    public class Blob
    {
        public CloudStorageAccount CloudStorageAccount { get; set; }

        public  CloudBlobClient CloudBlobClient { get; set; }

        public Blob(IConfiguration configuration)
        {
            CloudStorageAccount = CloudStorageAccount.Parse(configuration["BlobConnectionString"]);
            CloudBlobClient = CloudStorageAccount.CreateCloudBlobClient();
        }

        public async Task<CloudBlobContainer> GetContainer(string containerName)
        {
            CloudBlobContainer cbc = CloudBlobClient.GetContainerReference(containerName);
            await cbc.CreateIfNotExistsAsync();
            await cbc.SetPermissionsAsync(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });

            return cbc;

        }

        public async Task<CloudBlob> GetBlob(string imageName, string containerName)
        {
            CloudBlobContainer container = await GetContainer(containerName);

            CloudBlob blob = container.GetBlobReference(imageName);

            return blob;
        }

        public void UploadFile(CloudBlobContainer cloudBlobContainer, string filename, string filepath)
        {
            var blobFile = cloudBlobContainer.GetBlockBlobReference(filename);
            blobFile.UploadFromFileAsync(filepath);
        }
    }
}

InstaFit/Pages/FitnessPosts/Index.cshtml.cs
using InstaFit.Models;
using InstaFit.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace InstaFit.Pages.FitnessPosts
{
    public class IndexModel : PageModel
    {
        private readonly IFit _FitnessPost;

        public IndexModel(IFit fitnessPost)
        {
            _FitnessPost = fitnessPost;
        }

        [FromRoute]
        public int ID { get; set; }
        public FitnessPost FitnessPost { get; set; }



        public async Task OnGet()
        {
            FitnessPost = await _FitnessPost.FindFitnessPost(ID);
        }
    }
}

InstaFit/Pages/FitnessPosts/Manage.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using InstaFit.Models;
using InstaFit.Models.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using InstaFit.Models.utilites;
using Microsoft.WindowsAzure.Storage.Blob;

namespace InstaFit.Pages.FitnessPosts
{
    public class ManageModel : PageModel
    {
        private readonly IFit _fitnessPost;

        [FromRoute]
        public int? ID { get; set; }

        [BindProperty]
        public FitnessPost FitnessPost { get; set; }

        [BindProperty]
        public IFormFile Image { get; set; }

        public /*Models.utilites.*/Blob BlobImage { get; set; }

        public ManageModel(IFit fitnessPost, IConfiguration configuration)
        {
            _fitnessPost = fitnessPost;
            // blob storage account to be referenced
            BlobImage = new Blob(configuration);
        }


        public async Task OnGet()
        {
            FitnessPost = await _fitnessPost.FindFitnessPost(ID.GetValueOrDefault()) ?? new FitnessPost();
        }
        public async Task<IActionResult> OnPost()
        {
            var post = await _fitnessPost.FindFitnessPost(ID.GetValueOrDefault()) ?? new FitnessPost();

            post.Description = FitnessPost.Description;
            post.Location = FitnessPost.Location;

            if(Image != null)
            {
                var filepath = Path.GetTempFileName();
                using (var stream = new FileStream(filepath, FileMode.Create))
                {
                    await Image.CopyToAsync(stream);
                }
                // get container
                var container = await BlobImage.GetContainer("fitness");
                // upload image
                 BlobImage.UploadFile(container, Image.FileName, filepath);

                // Get the Image that we just uploaded

                CloudBlob blob = await BlobImage.GetBlob(Image.FileName, container.Name);

                // update the db image for the restaurant
                post.URL = blob.Uri.ToString();

            }

            await _fitnessPost.SaveAsync(post);

            return RedirectToPage("/FitnessPosts/Index", new { id = post.ID });
        }
        public async Task<IActionResult> OnPostDelete()
        {
            await _fitnessPost.DeleteAsync(ID.Value);
            return RedirectToPage("/Index");
        }
    }
}

InstaFit/Pages/FitnessPosts/Index.cshtml
@page "{id}"
@model InstaFit.Pages.FitnessPosts.IndexModel
@{
    Layout = "_Layout";

}
<div class="instagram-wrap">
    <div class="card">
        <div class="card-header">
            <div class="profile-img"></div>
            <div class="profile-info">
                <div class="name">Username</div>
                <div class="location">@Model.FitnessPost.Location</div>
            </div>
            <div class="time">
                1hr
            </div>
            <div class="content">
                <img src="@Model.FitnessPost.URL"/>
            </div>
            <div class="card-footer">
                <div class="likes">
                    45 likes
                </div>
                <div class="description">
                    <p>
                        <span class="username">Username</span> @Model.FitnessPost.Description
                    </p>
                </div>
                <div class="comments">
                    <p>
                        <span class="username">Danny32: </span>What was your workout!!??
                    </p>
                    <p>
                        <span class="username">BigRig722: </span> I love the Form!!
                    </p>
                </div>
                <div class="form">
                    <a asp-page="/FitnessPosts/Manage" asp-route-id="@Model.FitnessPost.ID">Edit Post</a>

                </div>
            </div>
        </div>
    </div>
</div>

InstaFit/Pages/FitnessPosts/Manage.cshtml
@page "{id?}"
@model InstaFit.Pages.FitnessPosts.ManageModel
@{
    ViewData["Title"] = "Manage";
    Layout = "_Layout";

}


<form method="post" enctype="multipart/form-data">

    <div class="instagram-wrap">
        <div class="card">
            <div class="card-header">
                <div class="profile-img"></div>
                <div class="profile-info">
                    <div class="name">Username</div>
                    <div class="location">
                        <label asp-for="FitnessPost.Location"></label>
                        <input asp-for="FitnessPost.Location" />
                    </div>
                </div>
                <div class="time">
                    1hr
                </div>
                <div class="content">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" type="file" />
                </div>
                <div class="card-footer">
                    <div class="likes">
                        45 likes
                    </div>
                    <div class="description">
                        <p>
                            <label asp-for="FitnessPost.Description"></label>
                            <textarea rows="5" asp-for="FitnessPost.Description"></textarea>
                        </p>
                    </div>
                    <div class="comments">
                        <p>
                            <span class="username">Danny32: </span>What was your workout!!??
                        </p>
                        <p>
                            <span class="username">BigRig722: </span> I love the Form!!
                        </p>
                    </div>
                    <div class="form">
                        <button type="submit">SAVE</button>
                        <button type="submit" asp-page-handler="Delete">DELETE</button>

                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

InstaFit/Pages/Index.cshtml
@page
@using InstaFit.Models.Interfaces

@inject IFit FitManagementService

@{
    var fitnessPosts = await FitManagementService.GetFitnessPosts();
    Layout = "_Layout";

}
<div class="toplogo">
    <p>

        <span class="headlogo">InstaFit</span> News Feed
    </p>
</div>


@foreach (var item in fitnessPosts)
{
    <div class="instagram-wrap">
        <div class="card">
            <div class="card-header">
                <div class="profile-img"></div>
                <div class="profile-info">
                    <div class="name">Username</div>
                    <div class="location">@item.Location</div>
                </div>
                <div class="time">
                    1hr
                </div>
                <div class="content">
                    <img src="@item.URL" />
                </div>
                <div class="card-footer">
                    <div class="likes">
                        45 likes
                    </div>
                    <div class="description">
                        <p>
                            <span class="username">Username</span> @item.Description
                        </p>
                    </div>
                    <div class="comments">
                        <p>
                            <span class="username">Danny32: </span>What was your workout!!??
                        </p>
                        <p>
                            <span class="username">BigRig722: </span> I love the Form!!
                        </p>
                    </div>
                    <div class="form">
                        <a asp-page="/FitnessPosts/Index" asp-route-id="@item.ID">Edit Post</a>

                    </div>
                </div>
            </div>
        </div>
    </div>

    
  
}

<a asp-page="/FitnessPosts/Manage">CREATE NEW POST</a>

InstaFit/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="~/style.css" />
</head>
<body>
    <section class="header-top">
        <p>InstaFIT</p>
    </section>

    <div>
        @RenderBody()
    </div>

    <section class="footer-bottom">
        <div class="social">
            <a asp-page="/Index"><i class="material-icons">home</i></a>
            <a href=""><i class="material-icons">search</i></a>
            <a asp-page="/FitnessPosts/Manage" ><i class="material-icons">add_box</i></a>
            <a href=""><i class="material-icons">favorite_border</i></a>
            <a href=""><i class="material-icons">account_circle</i></a>

        </div>
    </section>
</body>
</html>